name: spentree
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  another_telephony: ^0.4.1
  flutter_sms_inbox: ^1.0.4
  permission_handler: ^12.0.1
  local_auth: ^2.3.0
  shared_preferences: ^2.3.5

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  url_launcher: ^6.3.2
  phosphor_flutter: ^2.1.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  path_provider: ^2.1.5
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/appname.png
    - assets/dappname.png
    - assets/logo-name.png
    - assets/dlogo-name.png
    - assets/icons/navbg.png
    - assets/icons/dnavbg.png
    - assets/images/
    - assets/images/forest/
    - assets/icons/home.png
    - assets/icons/home_filled.png
    - assets/icons/analytics.png
    - assets/icons/analytics_filled.png
    - assets/icons/forest.png
    - assets/icons/forest_filled.png
    - assets/icons/profile.png
    - assets/icons/profile_filled.png
    - assets/audio/
    - assets/images/forest/spentwrap/
  
  fonts:
    - family: CalcioDemo
      fonts:
        - asset: assets/fonts/CalcioDemo.ttf
